[package]
name = "limin"
version = "0.1.0"
edition = "2021"

[build-dependencies]
fs_extra = "1.3.0"

[dependencies]
dunce = "1.0.2"
unicode-ident = "1.0.5"
phf = { version = "0.11.1", features = ["macros"] }
slotmap = "1.0.6"
indexmap = "1.9.3"
typed-arena = "2.0.2"
clap = { version = "4.2.1", features = ["derive"] }
semver = "1.0.17"