[package]
name = "limin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dunce = "1.0.2"
unicode-ident = "1.0.5"
phf = { version = "0.11.1", features = ["macros"] }
typed-arena = "2.0.1"